export const SERVER_URL = "https://meta-is-for-everyone.herokuapp.com"
export const SRC_HOST = "https://meta-is-for-everyone.herokuapp.com"
export const ADD = "Add"
export const ACCEPT = "Accept"
export const DENY = "Deny"